# Generated by Django 4.2.20 on 2025-03-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_meeting_options_meeting_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
    ]
